ekf_local_node:
  ros__parameters:
    use_sim_time: false
    two_d_mode: true
    publish_tf: true
    frequency: 15.0
    sensor_timeout: 0.5
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    odom0: /wheel/odometry
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false
    odom0_config: [false, false, false,
                   false, false, false,
                   true, false, false,
                   false, false, false,
                   false, false, false]

    imu0: /imu/data
    imu0_queue_size: 5
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false,  true,
                  false, false, false]
    imu0_nodelay: true
