amcl:
  ros__parameters:
    use_sim_time: false
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: scan
    set_initial_pose: false
    always_reset_initial_pose: false
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.1
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.2
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    laser_model_type: likelihood_field
    z_hit: 0.5
    z_rand: 0.5
    sigma_hit: 0.2
    do_beamskip: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /root/sensor_launch_ws/src/launch_all/maps/site1.yaml

lifecycle_manager_localization:
  ros__parameters:
    autostart: true
    node_names: ["map_server", "amcl"]

planner_server:
  ros__parameters:
    planner_plugins: ["SmacPlanner"]
    SmacPlanner:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      use_astar: false             # false = Dijkstra
      allow_unknown: true
      tolerance: 0.25
      downsample_costmap: true
      downsampling_factor: 2
      smooth_path: true

controller_server:
  ros__parameters:
    cmd_vel_topic: /cmd_vel_nav
    min_vel_x: 0.02
    max_vel_x: 0.30
    acc_lim_x: 0.5
    acc_lim_theta: 1.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.25
      max_linear_accel: 0.8
      lookahead_dist: 0.6
      min_lookahead_dist: 0.25
      max_lookahead_dist: 1.2
      allow_reversing: true

bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "navigate_w_replanning_time.xml"

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: false
    resolution: 0.05
    track_unknown_space: true
    footprint: "[[0.09525, 0.09], [0.09525, -0.09], [-0.09525, -0.09], [-0.09525, 0.09]]"
    plugins: ["static_layer","obstacle_layer","inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d/StaticLayer"
      map_subscribe_transient_local: true
    obstacle_layer:
      plugin: "nav2_costmap_2d/ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        marking: true
        clearing: true
        obstacle_range: 8.0
        raytrace_range: 10.0
        max_obstacle_height: 2.0
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      inflation_radius: 0.4

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    footprint: "[[0.09525, 0.09], [0.09525, -0.09], [-0.09525, -0.09], [-0.09525, 0.09]]"
    plugins: ["obstacle_layer","inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d/ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        marking: true
        clearing: true
        obstacle_range: 6.0
        raytrace_range: 8.0
        max_obstacle_height: 2.0
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      inflation_radius: 0.4
