slam_toolbox:
  ros__parameters:
    resolution: 0.05
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.017
    minimum_time_interval: 0.10
    map_update_interval: 5.0
    max_laser_range: 12.0
    scan_topic: /scan
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    use_odometry: true
    use_scan_matching: true

